process.env.DATABASE_URL ??= 'postgresql://postgres@localhost:5432/yechim_ai?schema=public';
process.env.NODE_ENV ??= 'test';
process.env.JWT_ACCESS_SECRET ??= 'test-only-access-secret-that-is-at-least-64-chars-01234567890123456789';
process.env.JWT_REFRESH_SECRET ??= 'test-only-refresh-secret-that-is-at-least-64-chars-98765432109876543210';
process.env.REQUEST_BODY_LIMIT ??= '1mb';
process.env.JWT_ACCESS_EXPIRES_IN ??= '15m';
process.env.JWT_REFRESH_EXPIRES_IN ??= '30d';
process.env.BCRYPT_SALT_ROUNDS ??= '10';
process.env.PASSWORD_RESET_EXPIRES_MINUTES ??= '30';
process.env.PORT ??= '3001';
process.env.FRONTEND_URL ??= 'http://localhost:5173';
delete process.env.TELEGRAM_API_ID;
delete process.env.TELEGRAM_API_HASH;
delete process.env.TELEGRAM_SESSION_ENCRYPTION_KEY;
delete process.env.GOOGLE_CLIENT_ID;
delete process.env.GOOGLE_CLIENT_SECRET;
delete process.env.GOOGLE_REDIRECT_URI;
delete process.env.GOOGLE_TOKEN_ENCRYPTION_KEY;
process.env.FILE_STORAGE_PROVIDER ??= 'local';
process.env.FILE_STORAGE_LOCAL_PATH ??= './test-uploads';
process.env.FILE_MAX_SIZE_MB ??= '20';
