import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

export const ACTIVITY_ACTIONS = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  REMINDER_CREATED: 'REMINDER_CREATED',
  MEETING_CREATED: 'MEETING_CREATED',
  NOTE_CREATED: 'NOTE_CREATED',
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  MEMORY_CREATED: 'MEMORY_CREATED',
  MEMORY_UPDATED: 'MEMORY_UPDATED',
  MEMORY_DELETED: 'MEMORY_DELETED',
  FINANCE_TRANSACTION_CREATED: 'FINANCE_TRANSACTION_CREATED',
  FINANCE_TRANSACTION_UPDATED: 'FINANCE_TRANSACTION_UPDATED',
  FINANCE_TRANSACTION_DELETED: 'FINANCE_TRANSACTION_DELETED',
  FINANCE_CATEGORY_CREATED: 'FINANCE_CATEGORY_CREATED',
  FINANCE_CATEGORY_UPDATED: 'FINANCE_CATEGORY_UPDATED',
  FINANCE_CATEGORY_DELETED: 'FINANCE_CATEGORY_DELETED',
  FINANCE_ACCOUNT_CREATED: 'FINANCE_ACCOUNT_CREATED',
  FINANCE_ACCOUNT_UPDATED: 'FINANCE_ACCOUNT_UPDATED',
  FINANCE_ACCOUNT_ARCHIVED: 'FINANCE_ACCOUNT_ARCHIVED',
  AI_TOOL_EXECUTED: 'AI_TOOL_EXECUTED',
  AI_AGENT_MESSAGE: 'AI_AGENT_MESSAGE',
  AI_AGENT_ACTION_CONFIRMED: 'AI_AGENT_ACTION_CONFIRMED',
  AI_AGENT_ACTION_CANCELLED: 'AI_AGENT_ACTION_CANCELLED',
  FILE_CONTENT_EXTRACTED: 'FILE_CONTENT_EXTRACTED',
  TELEGRAM_CONNECTED: 'TELEGRAM_CONNECTED',
  TELEGRAM_DISCONNECTED: 'TELEGRAM_DISCONNECTED',
  TELEGRAM_MESSAGE_SENT: 'TELEGRAM_MESSAGE_SENT',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  GOOGLE_CONNECTED: 'GOOGLE_CONNECTED',
  GOOGLE_DISCONNECTED: 'GOOGLE_DISCONNECTED',
  GOOGLE_CALENDAR_EVENT_CREATED: 'GOOGLE_CALENDAR_EVENT_CREATED',
  GOOGLE_CALENDAR_EVENT_UPDATED: 'GOOGLE_CALENDAR_EVENT_UPDATED',
  GOOGLE_CALENDAR_EVENT_DELETED: 'GOOGLE_CALENDAR_EVENT_DELETED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_BLOCKED: 'LOGIN_BLOCKED',
  REGISTERED: 'REGISTERED',
  REGISTER_FAILED: 'REGISTER_FAILED',
  REFRESH_SUCCEEDED: 'REFRESH_SUCCEEDED',
  LOGOUT_COMPLETED: 'LOGOUT_COMPLETED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  FOLDER_CREATED: 'FOLDER_CREATED',
  FOLDER_UPDATED: 'FOLDER_UPDATED',
  FOLDER_DELETED: 'FOLDER_DELETED',
} as const;

export type ActivityLogInput = {
  userId: string;
  action: string;
  entityType: string;
  entityId?: string;
  metadata?: Prisma.InputJsonValue;
};

@Injectable()
export class ActivityLogService {
  constructor(private readonly prisma: PrismaService) {}

  record(input: ActivityLogInput) {
    return this.prisma.activityLog.create({
      data: {
        userId: input.userId,
        action: input.action,
        entityType: input.entityType,
        entityId: input.entityId,
        metadata: input.metadata,
      },
    });
  }
}
