import { Injectable } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';

export const ACTIVITY_ACTIONS = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  REMINDER_CREATED: 'REMINDER_CREATED',
  MEETING_CREATED: 'MEETING_CREATED',
  NOTE_CREATED: 'NOTE_CREATED',
  CONTACT_CREATED: 'CONTACT_CREATED',
  CONTACT_UPDATED: 'CONTACT_UPDATED',
  CONTACT_DELETED: 'CONTACT_DELETED',
  MEMORY_CREATED: 'MEMORY_CREATED',
  MEMORY_UPDATED: 'MEMORY_UPDATED',
  MEMORY_DELETED: 'MEMORY_DELETED',
  MEMORY_ALL_DELETED: 'MEMORY_ALL_DELETED',
  MEMORY_PREFERENCE_UPDATED: 'MEMORY_PREFERENCE_UPDATED',
  FINANCE_TRANSACTION_CREATED: 'FINANCE_TRANSACTION_CREATED',
  FINANCE_TRANSACTION_UPDATED: 'FINANCE_TRANSACTION_UPDATED',
  FINANCE_TRANSACTION_DELETED: 'FINANCE_TRANSACTION_DELETED',
  FINANCE_CATEGORY_CREATED: 'FINANCE_CATEGORY_CREATED',
  FINANCE_CATEGORY_UPDATED: 'FINANCE_CATEGORY_UPDATED',
  FINANCE_CATEGORY_DELETED: 'FINANCE_CATEGORY_DELETED',
  FINANCE_ACCOUNT_CREATED: 'FINANCE_ACCOUNT_CREATED',
  FINANCE_ACCOUNT_UPDATED: 'FINANCE_ACCOUNT_UPDATED',
  FINANCE_ACCOUNT_ARCHIVED: 'FINANCE_ACCOUNT_ARCHIVED',
  FINANCE_BUDGET_CREATED: 'FINANCE_BUDGET_CREATED',
  FINANCE_BUDGET_UPDATED: 'FINANCE_BUDGET_UPDATED',
  FINANCE_BUDGET_DELETED: 'FINANCE_BUDGET_DELETED',
  AGENT_PREFERENCE_UPDATED: 'AGENT_PREFERENCE_UPDATED',
  AGENT_ACTION_EXPIRED: 'AGENT_ACTION_EXPIRED',
  BRIEFING_SENT: 'BRIEFING_SENT',
  BRIEFING_FAILED: 'BRIEFING_FAILED',
  PROACTIVE_SUGGESTION_CREATED: 'PROACTIVE_SUGGESTION_CREATED',
  PROACTIVE_SUGGESTION_DISMISSED: 'PROACTIVE_SUGGESTION_DISMISSED',
  PROACTIVE_SUGGESTION_SNOOZED: 'PROACTIVE_SUGGESTION_SNOOZED',
  AI_TOOL_EXECUTED: 'AI_TOOL_EXECUTED',
  AI_AGENT_MESSAGE: 'AI_AGENT_MESSAGE',
  AI_AGENT_ACTION_CONFIRMED: 'AI_AGENT_ACTION_CONFIRMED',
  AI_AGENT_ACTION_CANCELLED: 'AI_AGENT_ACTION_CANCELLED',
  AI_AGENT_ACTION_FAILED: 'AI_AGENT_ACTION_FAILED',
  FILE_CONTENT_EXTRACTED: 'FILE_CONTENT_EXTRACTED',
  TELEGRAM_CONNECTED: 'TELEGRAM_CONNECTED',
  TELEGRAM_DISCONNECTED: 'TELEGRAM_DISCONNECTED',
  TELEGRAM_MESSAGE_SENT: 'TELEGRAM_MESSAGE_SENT',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  GOOGLE_CONNECTED: 'GOOGLE_CONNECTED',
  GOOGLE_DISCONNECTED: 'GOOGLE_DISCONNECTED',
  GOOGLE_CALENDAR_EVENT_CREATED: 'GOOGLE_CALENDAR_EVENT_CREATED',
  GOOGLE_CALENDAR_EVENT_UPDATED: 'GOOGLE_CALENDAR_EVENT_UPDATED',
  GOOGLE_CALENDAR_EVENT_DELETED: 'GOOGLE_CALENDAR_EVENT_DELETED',
  BITO_CONNECTED: 'BITO_CONNECTED',
  BITO_DISCONNECTED: 'BITO_DISCONNECTED',
  BITO_TOOL_EXECUTED: 'BITO_TOOL_EXECUTED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_BLOCKED: 'LOGIN_BLOCKED',
  REGISTERED: 'REGISTERED',
  REGISTER_FAILED: 'REGISTER_FAILED',
  REFRESH_SUCCEEDED: 'REFRESH_SUCCEEDED',
  LOGOUT_COMPLETED: 'LOGOUT_COMPLETED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  FOLDER_CREATED: 'FOLDER_CREATED',
  FOLDER_UPDATED: 'FOLDER_UPDATED',
  FOLDER_DELETED: 'FOLDER_DELETED',
} as const;

export type ActivityLogInput = {
  userId: string;
  action: string;
  entityType: string;
  entityId?: string;
  metadata?: Prisma.InputJsonValue;
};

const MEANINGFUL_ACTIVITY_ACTIONS = new Set<string>([
  ACTIVITY_ACTIONS.TASK_CREATED,
  ACTIVITY_ACTIONS.TASK_COMPLETED,
  ACTIVITY_ACTIONS.REMINDER_CREATED,
  ACTIVITY_ACTIONS.MEETING_CREATED,
  ACTIVITY_ACTIONS.NOTE_CREATED,
  ACTIVITY_ACTIONS.CONTACT_CREATED,
  ACTIVITY_ACTIONS.CONTACT_UPDATED,
  ACTIVITY_ACTIONS.CONTACT_DELETED,
  ACTIVITY_ACTIONS.MEMORY_CREATED,
  ACTIVITY_ACTIONS.MEMORY_UPDATED,
  ACTIVITY_ACTIONS.MEMORY_DELETED,
  ACTIVITY_ACTIONS.MEMORY_ALL_DELETED,
  ACTIVITY_ACTIONS.MEMORY_PREFERENCE_UPDATED,
  ACTIVITY_ACTIONS.FINANCE_TRANSACTION_CREATED,
  ACTIVITY_ACTIONS.FINANCE_TRANSACTION_UPDATED,
  ACTIVITY_ACTIONS.FINANCE_TRANSACTION_DELETED,
  ACTIVITY_ACTIONS.FINANCE_CATEGORY_CREATED,
  ACTIVITY_ACTIONS.FINANCE_CATEGORY_UPDATED,
  ACTIVITY_ACTIONS.FINANCE_CATEGORY_DELETED,
  ACTIVITY_ACTIONS.FINANCE_ACCOUNT_CREATED,
  ACTIVITY_ACTIONS.FINANCE_ACCOUNT_UPDATED,
  ACTIVITY_ACTIONS.FINANCE_ACCOUNT_ARCHIVED,
  ACTIVITY_ACTIONS.FINANCE_BUDGET_CREATED,
  ACTIVITY_ACTIONS.FINANCE_BUDGET_UPDATED,
  ACTIVITY_ACTIONS.FINANCE_BUDGET_DELETED,
  ACTIVITY_ACTIONS.AGENT_PREFERENCE_UPDATED,
  ACTIVITY_ACTIONS.AI_TOOL_EXECUTED,
  ACTIVITY_ACTIONS.AI_AGENT_MESSAGE,
  ACTIVITY_ACTIONS.AI_AGENT_ACTION_CONFIRMED,
  ACTIVITY_ACTIONS.AI_AGENT_ACTION_CANCELLED,
  ACTIVITY_ACTIONS.TELEGRAM_CONNECTED,
  ACTIVITY_ACTIONS.TELEGRAM_DISCONNECTED,
  ACTIVITY_ACTIONS.TELEGRAM_MESSAGE_SENT,
  ACTIVITY_ACTIONS.GOOGLE_CONNECTED,
  ACTIVITY_ACTIONS.GOOGLE_DISCONNECTED,
  ACTIVITY_ACTIONS.GOOGLE_CALENDAR_EVENT_CREATED,
  ACTIVITY_ACTIONS.GOOGLE_CALENDAR_EVENT_UPDATED,
  ACTIVITY_ACTIONS.GOOGLE_CALENDAR_EVENT_DELETED,
  ACTIVITY_ACTIONS.BITO_CONNECTED,
  ACTIVITY_ACTIONS.BITO_DISCONNECTED,
  ACTIVITY_ACTIONS.BITO_TOOL_EXECUTED,
  ACTIVITY_ACTIONS.FILE_UPLOADED,
  ACTIVITY_ACTIONS.FILE_DELETED,
  ACTIVITY_ACTIONS.LOGIN_SUCCEEDED,
  ACTIVITY_ACTIONS.LOGOUT_COMPLETED,
  ACTIVITY_ACTIONS.PASSWORD_CHANGED,
  ACTIVITY_ACTIONS.FOLDER_CREATED,
  ACTIVITY_ACTIONS.FOLDER_UPDATED,
  ACTIVITY_ACTIONS.FOLDER_DELETED,
  ACTIVITY_ACTIONS.PROACTIVE_SUGGESTION_DISMISSED,
  ACTIVITY_ACTIONS.PROACTIVE_SUGGESTION_SNOOZED,
]);

const isMeaningfulActivity = (action: string): boolean =>
  MEANINGFUL_ACTIVITY_ACTIONS.has(action) || action.startsWith('ADMIN_');

@Injectable()
export class ActivityLogService {
  constructor(private readonly prisma: PrismaService) {}

  record(input: ActivityLogInput) {
    const occurredAt = new Date();
    const create = this.prisma.activityLog.create({
      data: {
        userId: input.userId,
        action: input.action,
        entityType: input.entityType,
        entityId: input.entityId,
        metadata: input.metadata,
        createdAt: occurredAt,
      },
    });
    if (!isMeaningfulActivity(input.action)) return create;
    return this.prisma.$transaction([
      create,
      this.prisma.user.update({ where: { id: input.userId }, data: { lastActivityAt: occurredAt } }),
    ]).then(([activity]) => activity);
  }
}
