export default () => ({
  nodeEnv: process.env.NODE_ENV ?? 'development',
  trustProxy: process.env.TRUST_PROXY === 'true',
  requestBodyLimit: process.env.REQUEST_BODY_LIMIT ?? '1mb',
  port: Number.parseInt(process.env.PORT ?? '3000', 10),
  frontendUrl: process.env.FRONTEND_URL,
  jwt: {
    accessSecret: process.env.JWT_ACCESS_SECRET,
    refreshSecret: process.env.JWT_REFRESH_SECRET,
    accessExpiresIn: process.env.JWT_ACCESS_EXPIRES_IN ?? '15m',
    refreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN ?? '30d',
  },
  bcryptSaltRounds: Number.parseInt(process.env.BCRYPT_SALT_ROUNDS ?? '12', 10),
  authTimingLogs: process.env.NODE_ENV !== 'production' && process.env.AUTH_TIMING_LOGS === 'true',
  passwordResetExpiresMinutes: Number.parseInt(process.env.PASSWORD_RESET_EXPIRES_MINUTES ?? '30', 10),
  storage: {
    provider: (process.env.FILE_STORAGE_PROVIDER ?? 'local').toUpperCase(),
    localPath: process.env.FILE_STORAGE_LOCAL_PATH ?? './uploads',
    maxSizeBytes: Number.parseInt(process.env.FILE_MAX_SIZE_MB ?? '20', 10) * 1024 * 1024,
    s3: {
      endpoint: process.env.S3_ENDPOINT,
      region: process.env.S3_REGION,
      bucket: process.env.S3_BUCKET,
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    },
  },
  telegram: {
    configured: [process.env.TELEGRAM_API_ID, process.env.TELEGRAM_API_HASH, process.env.TELEGRAM_SESSION_ENCRYPTION_KEY].every(Boolean),
    apiId: process.env.TELEGRAM_API_ID === undefined ? undefined : Number.parseInt(process.env.TELEGRAM_API_ID, 10),
    apiHash: process.env.TELEGRAM_API_HASH,
    sessionEncryptionKey: process.env.TELEGRAM_SESSION_ENCRYPTION_KEY,
  },
  google: {
    configured: [process.env.GOOGLE_CLIENT_ID, process.env.GOOGLE_CLIENT_SECRET, process.env.GOOGLE_REDIRECT_URI, process.env.GOOGLE_TOKEN_ENCRYPTION_KEY].every(Boolean),
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    redirectUri: process.env.GOOGLE_REDIRECT_URI,
    tokenEncryptionKey: process.env.GOOGLE_TOKEN_ENCRYPTION_KEY,
  },
  ai: {
    apiKey: process.env.OPENAI_API_KEY,
    model: process.env.OPENAI_MODEL ?? 'gpt-5-mini',
    transcribeModel: process.env.OPENAI_TRANSCRIBE_MODEL ?? 'gpt-4o-mini-transcribe',
    ttsModel: process.env.OPENAI_TTS_MODEL ?? 'gpt-4o-mini-tts',
    ttsVoice: process.env.OPENAI_TTS_VOICE ?? 'coral',
    baseUrl: process.env.OPENAI_BASE_URL ?? 'https://api.openai.com/v1',
    timeoutMs: Number.parseInt(process.env.AI_TIMEOUT_MS ?? '45000', 10),
  },
  email: {
    provider: (process.env.EMAIL_PROVIDER ?? 'noop').toLowerCase(),
    apiKey: process.env.RESEND_API_KEY,
    from: process.env.EMAIL_FROM,
  },
  monitoring: { sentryDsn: process.env.SENTRY_DSN },
  notificationCronSecret: process.env.NOTIFICATION_CRON_SECRET,
  agentCronSecret: process.env.AGENT_CRON_SECRET ?? process.env.NOTIFICATION_CRON_SECRET,
});
